package com.example.restcontroller;

import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class MyController {
    // Rest controller
    // the response is alway the HTML body
    // cannot return HTML files
    @RequestMapping("/")
    public String showMain() {
        return "<h1>Hello World</h1> <p> this is generated by a controller method </p>";
    }

    @RequestMapping("/test")
    public String showTest() {
        return "<h1>Testing</h1> <p> this is generated by a controller method </p>";
    }

}
