package com.example.securitybasic;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class MyController {
    @GetMapping("/")
    public String test() {
        return "Welcome to Spring Security";
    }
}

// the default user name is "user" and the pwd is generated by the spring
// container
