-- All countries


INSERT INTO `country` (`name`, `capital`) VALUES
('Afghanistan', 'Kabul'),
('Åland Islands', 'Mariehamn'),
('Albania', 'Tirana'),
('Algeria', 'Algiers'),
('American Samoa', 'Pago Pago'),
('Andorra', 'Andorra la Vella'),
('Angola', 'Luanda'),
('Anguilla', 'The Valley'),
('Antarctica', 'Antarctica'),
('Antigua and Barbuda', 'St. John\'s'),
('Argentina', 'Buenos Aires'),
('Armenia', 'Yerevan'),
('Aruba', 'Oranjestad'),
('Australia', 'Canberra'),
('Austria', 'Vienna'),
('Azerbaijan', 'Baku'),
('Bahamas', 'Nassau'),
('Bahrain', 'Manama'),
('Bangladesh', 'Dhaka'),
('Barbados', 'Bridgetown'),
('Belarus', 'Minsk'),
('Belgium', 'Brussels'),
('Belize', 'Belmopan'),
('Benin', 'Porto-Novo'),
('Bermuda', 'Hamilton'),
('Bhutan', 'Thimphu'),
('Bolivia (Plurinational State of)', 'Sucre'),
('Bosnia and Herzegovina', 'Sarajevo'),
('Botswana', 'Gaborone'),
('Bouvet Island', ''),
('Brazil', 'Brasilia'),
('British Indian Ocean Territory', 'Diego Garcia'),
('Brunei Darussalam', 'Bandar Seri Begawan'),
('Bulgaria', 'Sofia'),
('Burkina Faso', 'Ouagadougou'),
('Burundi', 'Bujumbura'),
('Cabo Verde', 'Praia'),
('Cambodia', 'Phnom Penh'),
('Cameroon', 'Yaounde'),
('Canada', 'Ottawa'),
('Caribbean Netherlands', 'Kralendijk'),
('Cayman Islands', 'George Town'),
('Central African Republic', 'Bangui'),
('Chad', 'N\'Djamena'),
('Chile', 'Santiago'),
('China', 'Beijing'),
('Christmas Island', 'Flying Fish Cove'),
('Cocos (Keeling) Islands', 'West Island'),
('Colombia', 'Bogota'),
('Comoros', 'Moroni'),
('Congo', 'Brazzaville'),
('Congo, Democratic Republic of the', 'Kinshasa'),
('Cook Islands', 'Avarua'),
('Costa Rica', 'San Jose'),
('Croatia', 'Zagreb'),
('Cuba', 'Havana'),
('Curaçao', 'Willemstad'),
('Cyprus', 'Nicosia'),
('Czech Republic', 'Prague'),
('Côte d\'Ivoire', 'Yamoussoukro'),
('Denmark', 'Copenhagen'),
('Djibouti', 'Djibouti'),
('Dominica', 'Roseau'),
('Dominican Republic', 'Santo Domingo'),
('Ecuador', 'Quito'),
('Egypt', 'Cairo'),
('El Salvador', 'San Salvador'),
('Equatorial Guinea', 'Malabo'),
('Eritrea', 'Asmara'),
('Estonia', 'Tallinn'),
('Eswatini (Swaziland)', 'Mbabane'),
('Ethiopia', 'Addis Ababa'),
('Falkland Islands (Malvinas)', 'Stanley'),
('Faroe Islands', 'Torshavn'),
('Fiji', 'Suva'),
('Finland', 'Helsinki'),
('France', 'Paris'),
('French Guiana', 'Cayenne'),
('French Polynesia', 'Papeete'),
('French Southern Territories', 'Port-aux-Francais'),
('Gabon', 'Libreville'),
('Gambia', 'Banjul'),
('Georgia', 'Tbilisi'),
('Germany', 'Berlin'),
('Ghana', 'Accra'),
('Gibraltar', 'Gibraltar'),
('Greece', 'Athens'),
('Greenland', 'Nuuk'),
('Grenada', 'St. George\'s'),
('Guadeloupe', 'Basse-Terre'),
('Guam', 'Hagatna'),
('Guatemala', 'Guatemala City'),
('Guernsey', 'St Peter Port'),
('Guinea', 'Conakry'),
('Guinea-Bissau', 'Bissau'),
('Guyana', 'Georgetown'),
('Haiti', 'Port-au-Prince'),
('Heard Island and Mcdonald Islands', ''),
('Honduras', 'Tegucigalpa'),
('Hong Kong', 'Hong Kong'),
('Hungary', 'Budapest'),
('Iceland', 'Reykjavik'),
('India', 'New Delhi'),
('Indonesia', 'Jakarta'),
('Iran', 'Tehran'),
('Iraq', 'Baghdad'),
('Ireland', 'Dublin'),
('Isle of Man', 'Douglas, Isle of Man'),
('Israel', 'Jerusalem'),
('Italy', 'Rome'),
('Jamaica', 'Kingston'),
('Japan', 'Tokyo'),
('Jersey', 'Saint Helier'),
('Jordan', 'Amman'),
('Kazakhstan', 'Astana'),
('Kenya', 'Nairobi'),
('Kiribati', 'Tarawa'),
('Korea, North', 'Pyongyang'),
('Korea, South', 'Seoul'),
('Kosovo', 'Pristina'),
('Kuwait', 'Kuwait City'),
('Kyrgyzstan', 'Bishkek'),
('Lao People\'s Democratic Republic', 'Vientiane'),
('Latvia', 'Riga'),
('Lebanon', 'Beirut'),
('Lesotho', 'Maseru'),
('Liberia', 'Monrovia'),
('Libya', 'Tripolis'),
('Liechtenstein', 'Vaduz'),
('Lithuania', 'Vilnius'),
('Luxembourg', 'Luxembourg'),
('Macao', 'Macao'),
('Macedonia North', 'Skopje'),
('Madagascar', 'Antananarivo'),
('Malawi', 'Lilongwe'),
('Malaysia', 'Kuala Lumpur'),
('Maldives', 'Male'),
('Mali', 'Bamako'),
('Malta', 'Valletta'),
('Marshall Islands', 'Majuro'),
('Martinique', 'Fort-de-France'),
('Mauritania', 'Nouakchott'),
('Mauritius', 'Port Louis'),
('Mayotte', 'Mamoudzou'),
('Mexico', 'Mexico City'),
('Micronesia', 'Palikir'),
('Moldova', 'Chisinau'),
('Monaco', 'Monaco'),
('Mongolia', 'Ulan Bator'),
('Montenegro', 'Podgorica'),
('Montserrat', 'Plymouth'),
('Morocco', 'Rabat'),
('Mozambique', 'Maputo'),
('Myanmar (Burma)', 'Nay Pyi Taw'),
('Namibia', 'Windhoek'),
('Nauru', 'Yaren'),
('Nepal', 'Kathmandu'),
('Netherlands', 'Amsterdam'),
('Netherlands Antilles', 'Willemstad'),
('New Caledonia', 'Noumea'),
('New Zealand', 'Wellington'),
('Nicaragua', 'Managua'),
('Niger', 'Niamey'),
('Nigeria', 'Abuja'),
('Niue', 'Alofi'),
('Norfolk Island', 'Kingston'),
('Northern Mariana Islands', 'Saipan'),
('Norway', 'Oslo'),
('Oman', 'Muscat'),
('Pakistan', 'Islamabad'),
('Palau', 'Melekeok'),
('Palestine', 'East Jerusalem'),
('Panama', 'Panama City'),
('Papua New Guinea', 'Port Moresby'),
('Paraguay', 'Asuncion'),
('Peru', 'Lima'),
('Philippines', 'Manila'),
('Pitcairn Islands', 'Adamstown'),
('Poland', 'Warsaw'),
('Portugal', 'Lisbon'),
('Puerto Rico', 'San Juan'),
('Qatar', 'Doha'),
('Reunion', 'Saint-Denis'),
('Romania', 'Bucharest'),
('Russian Federation', 'Moscow'),
('Rwanda', 'Kigali'),
('Saint Barthelemy', 'Gustavia'),
('Saint Helena', 'Jamestown'),
('Saint Kitts and Nevis', 'Basseterre'),
('Saint Lucia', 'Castries'),
('Saint Martin', 'Marigot'),
('Saint Pierre and Miquelon', 'Saint-Pierre'),
('Saint Vincent and the Grenadines', 'Kingstown'),
('Samoa', 'Apia'),
('San Marino', 'San Marino'),
('Sao Tome and Principe', 'Sao Tome'),
('Saudi Arabia', 'Riyadh'),
('Senegal', 'Dakar'),
('Serbia', 'Belgrade'),
('Serbia and Montenegro', 'Belgrade'),
('Seychelles', 'Victoria'),
('Sierra Leone', 'Freetown'),
('Singapore', 'Singapur'),
('Sint Maarten', 'Philipsburg'),
('Slovakia', 'Bratislava'),
('Slovenia', 'Ljubljana'),
('Solomon Islands', 'Honiara'),
('Somalia', 'Mogadishu'),
('South Africa', 'Pretoria'),
('South Georgia and the South Sandwich Islands', 'Grytviken'),
('South Sudan', 'Juba'),
('Spain', 'Madrid'),
('Sri Lanka', 'Colombo'),
('Sudan', 'Khartoum'),
('Suriname', 'Paramaribo'),
('Svalbard and Jan Mayen', 'Longyearbyen'),
('Sweden', 'Stockholm'),
('Switzerland', 'Berne'),
('Syria', 'Damascus'),
('Taiwan', 'Taipei'),
('Tajikistan', 'Dushanbe'),
('Tanzania', 'Dodoma'),
('Thailand', 'Bangkok'),
('Timor-Leste', 'Dili'),
('Togo', 'Lome'),
('Tokelau', ''),
('Tonga', 'Nuku\'alofa'),
('Trinidad and Tobago', 'Port of Spain'),
('Tunisia', 'Tunis'),
('Turkey (Türkiye)', 'Ankara'),
('Turkmenistan', 'Ashgabat'),
('Turks and Caicos Islands', 'Cockburn Town'),
('Tuvalu', 'Funafuti'),
('U.S. Outlying Islands', ''),
('Uganda', 'Kampala'),
('Ukraine', 'Kiev'),
('United Arab Emirates', 'Abu Dhabi'),
('United Kingdom', 'London'),
('United States', 'Washington'),
('Uruguay', 'Montevideo'),
('Uzbekistan', 'Tashkent'),
('Vanuatu', 'Port Vila'),
('Vatican City Holy See', 'Vatican City'),
('Venezuela', 'Caracas'),
('Vietnam', 'Hanoi'),
('Virgin Islands, British', 'Road Town'),
('Virgin Islands, U.S', 'Charlotte Amalie'),
('Wallis and Futuna', 'Mata Utu'),
('Western Sahara', 'El-Aaiun'),
('Yemen', 'Sanaa'),
('Zambia', 'Lusaka'),
('Zimbabwe', 'Harare');